### PR TITLE
fix: resolve category and subcategory navigation by lifting state to HomePage 

### LINKED ISSUE #2: Product category buttons not working
### Describe your issue

Category buttons are not loading different categories on clicking them.

### Steps to reproduce

Go to the home page of website. [link in Readme file]
click on any category. for example, fruits or vegetables.
you will see no changes, same components remains as it is

### What was the expected result?

Expected to load different component category if they exist.

### Put here any screenshots or videos (optional)

Image

### Would you like to work on this issue?

None

### PR DESCRIPTION
**Pull request by Mustansir-06**
Description
This PR addresses the issue where category buttons (Fruits, Vegetables, etc.) were not updating the content on the Home Page. The root cause was local state isolation within the Category and Subcategory components, which prevented the HomePage from detecting selection changes.

### Related Issue
Fixes #2

Changes Made
State Lifting: Moved activeCategory and activeSubCategory state from child components to src/pages/HomePage.jsx to centralize control.

Component Refactoring: Updated src/components/1/Category.jsx and src/components/2/Subcategory.jsx to be functional (controlled) components that receive state and setter functions via props.

Conditional Rendering: Implemented logic in HomePage.jsx to display the full store view when "All" is selected and a filtered category view when specific categories are clicked.

### CODE REVIEW

**Comment by sujeet9682** [comment]
And link the PR to issue while creating Pull request.
Fixes #(issue No)

File: src/pages/HomePage.jsx [hunk 1]
```diff
@@ -24,49 +31,72 @@ const HomePage = () => {
...
+      {/* Logic: If 'All' is selected, show the default landing page */}
+      {activeCategory === "All" ? (
+        <>
+          <HeroBanner />
+          <NewInStore />
+          <DailyItems />
+          <Everything99 />
+          <FeaturedProducts />
 
-      <div>
```
Comment (sujeet9682) [inline src/pages/HomePage.jsx]: try to do minimal required changes only. Don't remove and add the same code.

**Comment by sujeet9682** [comment]
Refer above conversation before creating Pull request. Hope it will help you.
